package lettre;

public class Dicos {
	
	static String[] dico3 = { "gag", "gai", "gaz", "gel", "gks", "gin", "gnu",
			"glu", "gui", "guy", "gre", "gue", "ace", "acm", "agi", "ait",
			"aie", "ail", "air", "and", "alu", "ami", "arc", "are", "art",
			"apr", "avr", "sur", "mat", "mur", "eme", "ere", "git", "ras",
			"reg", "rat", "raz", "roi", "rit", "riz", "roc", "rot", "roy",
			"rms", "rpc", "rut", "lat", "led", "lac", "lad", "lit", "let",
			"lob", "loi", "lib", "lin", "lis", "lot", "ltd", "lut", "lux",
			"lue", "lui", "fft", "lys", "fco", "far", "fat", "fer", "feu",
			"fez", "fig", "fil", "fin", "fit", "foc", "foi", "fol", "for",
			"fou", "fox", "fsf", "fui", "ftp", "fur", "fus", "fut", "age",
			"ame", "ref", "rot", "les", "fee", "fut", "quo", "kif", "kit",
			"que", "qui", "kir", "env", "eut", "eau", "ego", "edf", "erg",
			"est", "etc", "eue", "air", "art", "axe", "est", "eux", "val",
			"van", "ver", "vhs", "via", "vie", "vif", "ile", "vis", "vit",
			"vol", "vos", "vme", "age", "pal", "ane", "pic", "pis", "age",
			"ame", "vil", "vin", "pue", "pur", "put", "pre", "vue", "pue",
			"jas", "pcl", "jeu", "pan", "par", "pas", "peu", "pie", "pin",
			"jpl", "pot", "pou", "pli", "plu", "jus", "pua", "pub", "div",
			"jet", "job", "est", "duo", "dan", "dis", "dit", "dix", "don",
			"dot", "dru", "duc", "due", "dur", "dut", "ont", "vet", "ici",
			"ucb", "ont", "une", "usa", "use", "use", "oct", "ode", "oui",
			"uni", "ici", "des", "dec", "dep", "ohm", "oie", "ont", "osa",
			"ose", "ose", "cru", "inc", "ion", "ira", "iso", "ccd", "cal",
			"cap", "car", "cas", "cle", "cdn", "cep", "cet", "cil", "cit",
			"coi", "col", "coq", "cor", "cou", "cri", "cpt", "cpu", "cul",
			"cru", "une", "zoo", "the", "tac", "tex", "tex", "tir", "toc",
			"toi", "ton", "tri", "est", "est", "zen", "twm", "tut", "ncd",
			"net", "nid", "tcp", "tan", "nom", "nov", "tek", "tel", "ter",
			"tic", "top", "nue", "nui", "nul", "tva", "tua", "tue", "tuf",
			"hai", "tue", "nfs", "nec", "nef", "nez", "non", "bot", "hic",
			"hie", "bue", "hui", "bac", "bai", "bal", "ban", "bar", "bas",
			"bat", "ble", "bec", "bel", "bis", "bit", "boa", "bob", "bol",
			"bon", "box", "boy", "bru", "bsd", "but", "tel", "yak", "yen",
			"tot", "ont", "ecu", "sac", "sec", "sel", "ski", "sic", "six",
			"elu", "emu", "soc", "epi", "bat", "ete", "sua", "sud", "sun",
			"sut", "man", "max", "sgi", "set", "mie", "mis", "mit", "soi",
			"sol", "son", "sot", "sou", "mus", "suc", "sue", "sur", "bee",
			"sue", "mai", "mal", "mat", "men", "mer", "met", "mil", "min",
			"moi", "mol", "mon", "mot", "mou", "mme", "mur" };

	static String[] dico4 = { "drap", "nuee", "agit", "mais", "krak", "eric",
			"aaai", "agir", "drop", "dome", "buis", "rode", "puce", "roda",
			"drue", "buse", "bure", "rode", "haie", "hais", "hait", "puer",
			"hall", "role", "halo", "haro", "puis", "hase", "decu", "pull",
			"vais", "puma", "haut", "valu", "vain", "vase", "alea", "vamp",
			"thon", "vaux", "vaut", "afin", "fier", "fief", "mica", "fiel",
			"thym", "fini", "midi", "epie", "meat", "mien", "fisc", "miel",
			"film", "mike", "feru", "tige", "mise", "epia", "tele", "fevr",
			"tien", "miss", "mile", "tint", "aout", "fetu", "tilt", "mita",
			"tenu", "mite", "agio", "agir", "agit", "mite", "fele", "ogre",
			"fela", "fele", "meme", "pres", "pref", "aere", "tete", "pret",
			"tetu", "hele", "hote", "here", "foin", "mode", "font", "foot",
			"moka", "fond", "fora", "fort", "toge", "todd", "mont", "mord",
			"mors", "fore", "mort", "four", "toit", "tond", "moto", "tors",
			"tort", "moue", "moud", "aout", "yvan", "tome", "tord", "mous",
			"yves", "tous", "toux", "flan", "tour", "tout", "oeil", "veau",
			"utah", "utah", "flou", "flot", "heur", "vend", "venu", "vent",
			"velu", "oeuf", "vers", "vert", "flux", "veto", "veuf", "veut",
			"veux", "hale", "hale", "etal", "etai", "etat", "etau", "hata",
			"hate", "ores", "have", "buee", "hate", "jusa", "hair", "etui",
			"aire", "frac", "frai", "fret", "trie", "cade", "tram", "fris",
			"frit", "froc", "cage", "cadi", "trac", "duel", "jade", "cake",
			"tria", "cane", "dune", "camp", "trio", "dura", "cafe", "troc",
			"mole", "came", "trot", "jais", "rude", "trop", "trou", "aine",
			"ruer", "janv", "tole", "jase", "jars", "jasa", "dure", "truc",
			"java", "jazz", "jase", "rush", "tsar", "epee", "clot", "aile",
			"aigu", "aide", "aine", "hele", "hier", "aile", "vice", "vecu",
			"aise", "aera", "hela", "vint", "viol", "aise", "visa", "vise",
			"aere", "hetu", "vive", "vite", "velo", "ange", "once", "vise",
			"anis", "anon", "onde", "anse", "ansi", "anus", "onze", "cene",
			"vetu", "onyx", "cepe", "hors", "home", "ceci", "houx", "vois",
			"voir", "voit", "voeu", "voix", "cout", "houe", "voie", "volt",
			"vont", "jean", "coit", "cens", "alfa", "cent", "allo", "vote",
			"vous", "cerf", "cern", "aloi", "jerk", "ceux", "jeun", "alto",
			"vlsi", "amas", "amen", "amer", "ames", "omet", "omis", "omit",
			"arcs", "caid", "oral", "orge", "vrac", "vrai", "fuel", "ardu",
			"ardt", "fuit", "chas", "char", "orme", "aria", "chef", "hote",
			"laid", "sage", "lait", "land", "muni", "tuer", "mule", "lama",
			"lard", "ores", "laps", "turc", "turf", "lame", "fuir", "chai",
			"chah", "sapa", "chat", "mure", "muer", "muet", "full", "sake",
			"cher", "chez", "saga", "saur", "oser", "chic", "tuez", "lame",
			"choc", "chou", "mura", "musc", "muse", "sain", "sais", "sait",
			"sana", "sang", "sans", "sali", "apex", "fute", "sari", "sape",
			"chut", "sauf", "saut", "sape", "osez", "saxo", "jill", "ciel",
			"cinq", "cime", "opus", "apre", "opte", "apte", "opta", "opte",
			"aval", "cola", "john", "lese", "jonc", "joli", "cote", "coco",
			"tres", "coke", "coin", "conf", "seau", "colt", "seme", "coma",
			"avec", "aveu", "avez", "corp", "joie", "cosy", "clip", "avis",
			"seme", "lest", "sein", "coud", "coup", "cour", "sens", "sent",
			"self", "sera", "serf", "seve", "sers", "zele", "sert", "cote",
			"type", "joug", "typo", "jour", "auto", "ubac", "ovni", "owen",
			"legs", "clam", "clan", "clef", "aube", "lent", "clin", "soul",
			"clos", "clou", "sema", "leur", "sept", "club", "seul", "type",
			"sexe", "sexy", "skie", "ucla", "crue", "atre", "gain", "huit",
			"gang", "hune", "gala", "gale", "naja", "html", "cote", "nain",
			"cran", "shah", "laic", "aube", "cric", "crin", "cris", "croc",
			"auge", "skia", "cone", "audy", "aune", "huer", "crut", "aura",
			"cote", "gant", "oued", "lice", "auto", "gars", "nais", "lift",
			"lien", "ours", "nasa", "lion", "sied", "nazi", "lira", "lire",
			"zebu", "lise", "lisp", "show", "zele", "lesa", "zinc", "zero",
			"azur", "lied", "lier", "lieu", "lino", "sien", "snob", "silo",
			"sire", "site", "lese", "oree", "gene", "sofa", "loin", "loir",
			"long", "lors", "soif", "axer", "soir", "ieee", "ayez", "zone",
			"sole", "soli", "sors", "loup", "zona", "zone", "zoom", "gout",
			"noel", "souk", "soya", "mans", "gere", "soda", "soja", "neuf",
			"soin", "soit", "ieee", "sono", "sont", "ibid", "ibis", "geai",
			"solo", "slip", "loto", "sort", "slow", "gens", "nerf", "elle",
			"nait", "naif", "ouie", "ouir", "cube", "erra", "bail", "bain",
			"cuir", "gata", "gate", "judo", "pack", "jube", "gate", "page",
			"juin", "pane", "quel", "jury", "jupe", "paon", "cure", "pars",
			"paru", "baba", "cuba", "paul", "gite", "watt", "erre", "apic",
			"cube", "cuis", "cuit", "banc", "bang", "jude", "quai", "cure",
			"basa", "base", "juif", "erre", "cuti", "baud", "baux", "pain",
			"pair", "paix", "quoi", "pale", "base", "jute", "parc", "pari",
			"part", "papa", "pape", "neon", "pays", "esse", "gere", "spie",
			"spot", "neve", "gena", "nier", "girl", "unir", "unit", "unix",
			"gera", "noce", "gond", "hifi", "gene", "pere", "noir", "noix",
			"gnon", "nord", "gene", "nous", "ieee", "peau", "idem", "ides",
			"pend", "goal", "perd", "perl", "pers", "peur", "peut", "ebat",
			"gong", "golf", "pese", "pese", "beau", "pame", "glas", "pale",
			"pama", "pame", "ilot", "pate", "pesa", "stem", "echo", "echu",
			"pate", "ecot", "swap", "ecru", "gras", "bale", "stuc", "grog",
			"gros", "urge", "bati", "daim", "luge", "atil", "race", "dame",
			"urne", "etes", "rame", "luit", "suez", "luxe", "kart", "etre",
			"star", "raid", "suce", "suif", "rail", "suis", "suit", "suiv",
			"rang", "luth", "rare", "surf", "phil", "stop", "yard", "grec",
			"greg", "user", "gril", "gris", "beat", "dada", "dais", "lune",
			"grue", "kaki", "pied", "dard", "pieu", "daze", "lune", "urge",
			"yack", "suer", "lump", "race", "suie", "rama", "rame", "rami",
			"rapt", "luxa", "luxe", "rave", "rata", "rate", "indu", "usez",
			"bien", "pneu", "beer", "bebe", "bile", "bise", "pige", "exil",
			"pion", "egal", "pire", "pipe", "inca", "pise", "boxe", "idee",
			"inne", "ions", "pois", "poix", "inox", "pool", "poli", "dela",
			"insu", "port", "beta", "bete", "pope", "edam", "pene", "pouf",
			"pour", "poux", "bock", "edit", "kent", "rein", "bois", "boit",
			"bond", "boni", "plan", "iode", "boom", "bord", "iode", "bouc",
			"boue", "boul", "bous", "bout", "poil", "pond", "pont", "boxa",
			"boxe", "polo", "iota", "porc", "pore", "yeux", "plut", "dent",
			"demi", "bleu", "blet", "rene", "lynx", "bloc", "lyre", "lyse",
			"deux", "rala", "rale", "rend", "plat", "utah", "plot", "elle",
			"suca", "bref", "irai", "imbu", "rale", "irez", "iris", "fame",
			"irmx", "guet", "pris", "prit", "prix", "imsl", "tact", "nuit",
			"malt", "mare", "mari", "taie", "tain", "bras", "tank", "taon",
			"talc", "ntsc", "maux", "bric", "brie", "item", "brio", "brin",
			"bris", "broc", "brou", "taux", "face", "unir", "fade", "fane",
			"irmx", "mach", "brun", "brut", "rhum", "deja", "faim", "mage",
			"fais", "fait", "fana", "fane", "unir", "faon", "uucp", "pole",
			"fard", "fart", "mail", "main", "dine", "khan", "marc", "mark",
			"mars", "isba", "faut", "dina", "faux", "dine", "tais", "tait",
			"tant", "dery", "rien", "dime", "riez", "kilt", "math", "tare",
			"tard", "reel", "tapi", "ring", "maya", "rira", "rire", "tare",
			"taxi", "issu", "dick", "rite", "defi", "dieu", "deni", "dira",
			"dire", "dise", "rime", "king", "kilo", "dito", "reer", "kiwi",
			"rima", "kepi", "rime", "uree", "dois", "donc", "rock", "rixe",
			"dors", "dose", "kola", "dota", "acte", "rond", "roll", "dose",
			"gres", "ivre", "rene", "dock", "fend", "roux", "teck", "dodu",
			"mens", "ment", "deca", "doit", "abat", "feue", "dont", "recu",
			"tend", "feve", "tenu", "dort", "dosa", "abbe", "meus", "meut",
			"test", "doux", "yoga", "abus", "abri", "dote", "doue", "rose",
			"abus", "elan", "roue", "mout", "fera", "rose", "ocre", "roue",
			"menu", "elit", "elis", "elle", "obus", "mess", "male", "elue",
			"elut", "acre", "acre", "acte", "emet", "emit", "emir", "emis",
			"emoi", "item", "oter", "emue", "emut" };

	static String[] dico5 = { "lagon", "bagou", "fagot", "ragot", "bagne",
			"pagne", "mugir", "nagle", "globe", "facon", "nuque", "leste",
			"lesta", "zeste", "pesta", "peste", "veste", "bonus", "kyste",
			"tonus", "honte", "grace", "exact", "tonte", "bague", "dague",
			"vague", "diner", "bonze", "dinez", "leste", "peste", "bonte",
			"ponte", "clone", "bague", "close", "glose", "clora", "clore",
			"alors", "duvet", "buvez", "clown", "mirer", "radar", "obese",
			"airer", "cirer", "ilote", "badge", "usiez", "zebre", "repos",
			"obere", "giron", "osier", "osiez", "rader", "radis", "apres",
			"sirop", "radio", "badin", "jadis", "gypse", "audit", "repue",
			"tribu", "asile", "brick", "ladre", "brian", "trier", "prier",
			"guere", "frigo", "aller", "boots", "triez", "tetee", "usite",
			"tripe", "sisal", "tolle", "brisa", "brise", "miser", "frira",
			"frire", "leche", "voler", "achat", "amuir", "bolet", "volet",
			"folie", "polka", "avoir", "polir", "oisif", "polio", "folio",
			"polit", "oison", "brise", "offre", "gober", "folle", "suent",
			"cobol", "ouest", "sobre", "suera", "cobra", "queue", "queux",
			"sueur", "etend", "etude", "shako", "chaos", "chair", "bombe",
			"lever", "luter", "roman", "acces", "neveu", "devez", "buter",
			"chant", "juter", "champ", "domey", "devin", "devis", "lutin",
			"scier", "butin", "acier", "acide", "chape", "butor", "bombe",
			"vomir", "genet", "cedex", "chaud", "sujet", "chaux", "gemir",
			"devra", "homme", "scion", "pomme", "tomme", "osons", "usons",
			"rompe", "probe", "rompt", "romps", "rompu", "futur", "cocon",
			"lutte", "hutte", "butte", "lutta", "offre", "socle", "lutte",
			"ovine", "aviez", "avine", "avide", "creer", "broie", "froid",
			"proie", "front", "droit", "trois", "promu", "greer", "ovine",
			"prose", "tronc", "serie", "avion", "islam", "broye", "trope",
			"hevea", "capre", "serac", "avisa", "avise", "aviso", "forer",
			"brown", "dorer", "foret", "forez", "troua", "tordu", "horde",
			"troue", "proue", "gerer", "toril", "azure", "crepu", "aerer",
			"gerez", "aerez", "doris", "broya", "toron", "horne", "fakir",
			"porno", "seria", "serie", "norme", "dorme", "dormi", "troue",
			"avise", "torse", "merou", "torve", "forum", "porto", "serum",
			"grele", "grele", "jeter", "roser", "civet", "avril", "grela",
			"doser", "dosez", "poser", "peton", "nefle", "petit", "jeton",
			"civil", "arbre", "rosir", "mythe", "gesir", "crete", "arete",
			"scoop", "bosse", "fosse", "rosse", "bossu", "arbre", "score",
			"bette", "dette", "scout", "ether", "bahut", "fosse", "alpin",
			"alpha", "agres", "faite", "avoir", "avons", "obeir", "obera",
			"jeudi", "negre", "arche", "raidi", "jeune", "regne", "doper",
			"toper", "suiez", "deuil", "sucee", "sepia", "heurt", "pegre",
			"gueer", "vainc", "lopin", "soule", "obere", "veule", "taise",
			"faire", "heure", "begue", "taira", "soula", "haine", "ordre",
			"suint", "raire", "paire", "taire", "soule", "cuise", "guise",
			"ordre", "cuira", "suivi", "cuire", "check", "suive", "etiez",
			"suite", "murir", "couta", "peche", "gitan", "ranch", "nanan",
			"puree", "fanal", "coute", "reche", "rance", "banco", "luxer",
			"luxez", "duree", "essai", "banal", "faner", "citer", "miter",
			"assez", "lande", "tanne", "pecha", "peche", "tango", "fange",
			"assis", "paner", "panda", "vanne", "dandy", "essor", "banjo",
			"mitre", "tanin", "assit", "sunos", "danse", "panse", "fanon",
			"panne", "vanne", "munit", "munir", "roque", "toque", "sunos",
			"dansa", "pansa", "mater", "jante", "nanti", "vante", "tante",
			"loque", "krach", "homme", "guepe", "gater", "issue", "gatez",
			"panse", "vanta", "crack", "crabe", "arabe", "kraft", "azyme",
			"danse", "orage", "vante", "tuyau", "grade", "craie", "irait",
			"fuyez", "grain", "nover", "grade", "grand", "ocrer", "lover",
			"modal", "concu", "bovin", "modem", "godet", "aspic", "crawl",
			"sevir", "goder", "coder", "ioder", "ceint", "seing", "geins",
			"geint", "suons", "exces", "ecole", "email", "quota", "ecole",
			"aider", "seize", "texan", "exigu", "affut", "exile", "emaux",
			"edile", "avril", "modus", "percu", "etole", "vexer", "texas",
			"palan", "valez", "palet", "valet", "balai", "arome", "exila",
			"palme", "caban", "dalle", "talon", "falot", "palot", "thuya",
			"haler", "sable", "taler", "halle", "genou", "dalle", "mener",
			"genet", "mulot", "mulet", "culer", "fallu", "mibas", "valsa",
			"cabas", "sulky", "aider", "texte", "jalon", "sabir", "genre",
			"sabot", "palme", "valve", "dalla", "value", "culot", "talus",
			"valse", "valut", "sable", "menue", "cabri", "senti", "alter",
			"soeur", "halte", "urger", "mente", "total", "sente", "menti",
			"culte", "valse", "jambe", "coeur", "ombre", "cense", "sense",
			"urgea", "totem", "ergot", "dotez", "roter", "orgie", "athee",
			"ramez", "lamer", "hamac", "ramer", "taiga", "metal", "geoff",
			"rotin", "lotir", "argot", "doter", "noter", "voter", "rotor",
			"chale", "damer", "potin", "paien", "jamie", "cacao", "tamis",
			"heure", "metis", "lampe", "rampe", "sache", "yacht", "lotus",
			"orgue", "seoir", "cumin", "haira", "notre", "votre", "metro",
			"rampe", "laius", "hampe", "rampa", "pampa", "chien", "chier",
			"hotte", "lotte", "cumul", "sacre", "farce", "parce", "chine",
			"chiot", "exode", "rougi", "varan", "douce", "haras", "pouce",
			"sacre", "jouet", "louer", "nouer", "jouer", "joual", "rouer",
			"barbe", "mural", "barbu", "rouge", "mixer", "douer", "large",
			"barge", "houer", "fouet", "touer", "vouer", "houde", "pinup",
			"fouir", "ordre", "aurai", "harem", "tarif", "ourdi", "tarer",
			"parer", "tarir", "surgi", "farda", "epais", "hardi", "chips",
			"selle", "epave", "ourle", "louis", "jouir", "rouir", "joule",
			"geler", "celer", "farde", "muret", "curer", "murer", "amene",
			"aurez", "murez", "epate", "baril", "surir", "round", "lourd",
			"selon", "melon", "paroi", "epars", "baron", "houle", "boule",
			"poule", "tarot", "darne", "ardue", "pouls", "voulu", "bouse",
			"parmi", "larme", "bourg", "ourse", "epate", "poupe", "jarre",
			"curry", "toute", "celle", "larve", "barry", "harry", "louve",
			"douve", "parue", "harpe", "douze", "mixte", "joute", "loupe",
			"parut", "parti", "tarte", "celui", "larve", "etron", "crois",
			"croit", "grenu", "credo", "laser", "jaser", "raser", "semez",
			"basic", "creux", "nasse", "amour", "ester", "baser", "basez",
			"semer", "muser", "estoc", "creva", "semis", "cohue", "basse",
			"fasse", "lasso", "gemme", "astre", "choir", "stage", "aussi",
			"image", "stade", "papal", "merci", "creve", "gerbe", "faste",
			"vaste", "short", "emeus", "usuel", "emeut", "taper", "emeri",
			"sitot", "serez", "lapin", "lapis", "tapir", "tapit", "choie",
			"otage", "choix", "staff", "gerce", "serin", "shoot", "supin",
			"gaffe", "gerce", "chose", "choye", "serai", "merle", "laper",
			"serge", "chope", "statu", "stand", "moins", "super", "choux",
			"serpe", "moire", "servi", "japon", "truie", "bruit", "choya",
			"moite", "brume", "usure", "merlu", "mafia", "moine", "coing",
			"nappe", "moire", "geole", "envie", "prude", "nappe", "bruir",
			"fruit", "prune", "coite", "trust", "magie", "angle", "magot",
			"laque", "chene", "vaqua", "boxer", "foret", "boxez", "macon",
			"octet", "geste", "sonar", "actif", "objet", "monde", "joyau",
			"noyau", "boyau", "gager", "camee", "laval", "foyer", "voyez",
			"messe", "connu", "navet", "conge", "laver", "haver", "wagon",
			"paver", "ictus", "magma", "vaque", "cuver", "ravin", "voyou",
			"annee", "laque", "vaque", "conte", "sitin", "adage", "havre",
			"royal", "loyal", "ouvre", "naval", "conte", "doyen", "boyer",
			"loyer", "noyer", "josee", "baver", "ocean", "grime", "doyon",
			"lavis", "ravir", "iriez", "pavot", "cadet", "urine", "potee",
			"meteo", "seche", "stele", "stere", "hotel", "entre", "egard",
			"grief", "crier", "rotir", "ouvre", "caduc", "aride", "molle",
			"ovule", "aequo", "madre", "griot", "notre", "votre", "crime",
			"steak", "crise", "meche", "natal", "fatal", "golfe", "grive",
			"ratez", "rater", "latex", "latex", "abord", "colin", "colis",
			"emile", "irise", "ratio", "latin", "colon", "raton", "tweed",
			"comme", "sevra", "major", "emise", "tibia", "latte", "patte",
			"orner", "colza", "essai", "bible", "fibre", "okapi", "bouee",
			"daube", "dater", "skate", "groom", "stemm", "autel", "muter",
			"natif", "datif", "patin", "patio", "moral", "mutin", "outil",
			"momie", "sorel", "vicie", "jaune", "mords", "autre", "taule",
			"cajou", "morin", "pause", "jatte", "coron", "abces", "batte",
			"datte", "battu", "hibou", "taupe", "morse", "ukase", "comte",
			"libre", "obier", "riche", "sevre", "cajun", "encan", "encas",
			"morve", "croie", "groin", "crois", "croit", "croix", "comte",
			"morue", "rable", "bauge", "sorti", "iront", "irons", "sorbe",
			"tache", "cross", "sbire", "anche", "oncle", "goret", "corne",
			"mordu", "faune", "jauni", "rable", "baume", "paume", "tacha",
			"tache", "ecran", "morne", "corne", "cornu", "sosie", "etude",
			"odeur", "moshe", "fauve", "corsa", "corse", "ricin", "vicia",
			"vicie", "biche", "faute", "vichy", "fichu", "licol", "licou",
			"corps", "cahot", "gosse", "epier", "epieu", "epiez", "aorte",
			"epice", "lazzi", "corse", "bazar", "feler", "ombre", "ambre",
			"veler", "lepre", "epice", "ombre", "elire", "meule", "seule",
			"meure", "cosse", "meurs", "cossu", "saint", "riais", "riait",
			"cette", "liane", "piano", "meute", "riant", "stick", "snack",
			"amble", "armer", "tiare", "beler", "errez", "abois", "imbue",
			"obole", "extra", "levre", "abord", "ambre", "curee", "canal",
			"zebre", "embue", "seuil", "caner", "otite", "peche", "anaux",
			"meurt", "maint", "biais", "meuve", "recif", "pecha", "peche",
			"maire", "dechu", "liant", "debit", "errer", "diapo", "enfer",
			"sante", "rebus", "taxer", "rayer", "enfin", "vecut", "pareo",
			"angie", "engin", "utile", "musee", "steno", "ongle", "epoux",
			"hayon", "canoe", "emacs", "cedre", "leche", "canif", "enfui",
			"viger", "piger", "canon", "canot", "canna", "manne", "canne",
			"lifia", "vigie", "ganse", "ligne", "digne", "vigne", "stock",
			"recit", "lecha", "rifle", "coque", "decor", "fifre", "hydre",
			"tigre", "mante", "saoul", "smash", "ideal", "digue", "gerca",
			"vecue", "bayer", "layer", "payer", "colon", "tigre", "plaie",
			"cigit", "objet", "flanc", "mimai", "blanc", "plana", "store",
			"angle", "rayon", "saler", "payse", "aucun", "salin", "malin",
			"image", "figer", "vider", "rider", "indue", "salir", "galbe",
			"salle", "digit", "pigne", "amant", "hyene", "image", "neant",
			"adieu", "plage", "figue", "index", "annee", "plane", "idiot",
			"atone", "plaid", "flair", "blais", "plais", "atome", "galbe",
			"endos", "atoll", "egide", "plant", "flash", "caler", "galet",
			"flapi", "atout", "gamin", "bidet", "salit", "salon", "peage",
			"galon", "galop", "calot", "malle", "blase", "andre", "bidon",
			"tiens", "labas", "vient", "oxyda", "atlas", "calva", "salve",
			"beant", "malus", "sexue", "salut", "tiers", "oxyde", "lieue",
			"rieur", "epris", "eprit", "souci", "eleve", "iambe", "gamba",
			"samba", "pieta", "maman", "motel", "coter", "marge", "amene",
			"garer", "camer", "gamet", "opale", "motif", "cotir", "sparc",
			"coton", "skiez", "skier", "regal", "carie", "marin", "legat",
			"moulu", "vieil", "gamme", "souri", "sourd", "court", "viens",
			"rient", "tient", "carre", "marri", "oxyde", "motte", "cotte",
			"sotte", "regir", "orvet", "giter", "camus", "soute", "regna",
			"pieux", "vieux", "marte", "lieux", "rever", "enjeu", "soucy",
			"strie", "couac", "carie", "garce", "idole", "anjou", "gouge",
			"carat", "bebop", "cargo", "niece", "piece", "carne", "mardi",
			"skiff", "index", "caria", "legal", "liege", "coude", "piege",
			"marne", "goulu", "garni", "couse", "tiede", "lycee", "cousu",
			"leger", "coure", "gourd", "cours", "couru", "regne", "bijou",
			"soupa", "soupe", "jusau", "strie", "carpe", "egout", "diese",
			"soupe", "carte", "biere", "ortie", "encas", "carre", "diete",
			"decue", "decut", "caser", "fleur", "pleur", "capot", "oasis",
			"tuber", "amene", "rubin", "pubis", "amene", "amena", "vetez",
			"caste", "admet", "vetir", "admis", "admit", "plein", "hetre",
			"vetue", "eleva", "caper", "saper", "duche", "sapin", "bleue",
			"pleut", "ruban", "kapok", "unite", "eleve", "lucie", "gruau",
			"eclot", "lubie", "rubis", "cruel", "feter", "ondee", "plebe",
			"ecart", "vetit", "grume", "fucus", "union", "moyen", "soyez",
			"fjord", "caver", "savez", "linge", "unira", "tetue", "eleve",
			"emule", "video", "ennui", "dinde", "linda", "riiez", "ducal",
			"finir", "finit", "evasa", "evase", "nylon", "anise", "alain",
			"enbut", "huche", "ruche", "evase", "tinte", "hydro", "hydro",
			"plait", "lucre", "tinte", "squaw", "flana", "moyeu", "obtus",
			"final", "gaver", "nuage", "dingo", "vingt", "ruade", "rions",
			"biner", "viner", "hindi", "fiole", "savon", "viola", "puait",
			"poeme", "puant", "alain", "plier", "smith", "catch", "recto",
			"recta", "tinta", "pinte", "anode", "recru", "abusa", "mater",
			"abuse", "flane", "agate", "aieul", "filme", "deces", "aieux",
			"gnome", "matir", "pyrex", "tilde", "flane", "amibe", "filin",
			"agave", "abuse", "pilon", "viole", "hymen", "filma", "diode",
			"villa", "ville", "recel", "inoui", "hymne", "cible", "raler",
			"piege", "tuais", "tuait", "arret", "omise", "sauce", "palir",
			"tuant", "inmos", "etait", "palot", "rioux", "sauge", "cycle",
			"match", "poete", "penal", "renal", "limer", "rimer", "rugby",
			"piete", "bilan", "lilas", "tyran", "flirt", "gaule", "saule",
			"elite", "limon", "luger", "gicle", "elira", "elire", "breme",
			"tenia", "satin", "matin", "filer", "biler", "filet", "catir",
			"elise", "piler", "frere", "tenor", "rugir", "mauve", "filon",
			"miche", "filou", "pilou", "breve", "sauta", "spice", "gibet",
			"frete", "bille", "fille", "micro", "tenue", "venus", "gache",
			"veaux", "rirai", "haler", "gazer", "flore", "mazer", "gener",
			"genez", "direz", "tirer", "virer", "tiret", "typer", "floua",
			"gazon", "cable", "oubli", "opium", "typon", "eveil", "floue",
			"venal", "sauna", "cabla", "cable", "buggy", "aphte", "timon",
			"juger", "saura", "benin", "virus", "benir", "benit", "penis",
			"amont", "meler", "eloge", "scene", "ayant", "usage", "fleau",
			"gicla", "gicle", "amour", "pamez", "pamer", "saute", "inria",
			"opine", "ondit", "fugue", "echer", "flood", "visez", "riser",
			"lisez", "blond", "ebene", "plomb", "denue", "opine", "opina",
			"telex", "viral", "dirai", "lirai", "heler", "hobby", "tison",
			"spire", "gacha", "gache", "rirez", "lirez", "felix", "floue",
			"lober", "rober", "judas", "viril", "jobin", "tuent", "firme",
			"lecon", "tuera", "noble", "agent", "etape", "recut", "piper",
			"riper", "input", "phare", "poche", "vocal", "seche", "disco",
			"bleme", "nocif", "lippe", "echec", "delai", "biser", "hippy",
			"viser", "poche", "lobby", "helez", "secha", "vison", "bison",
			"velin", "felin", "preau", "album", "felon", "tissu", "ohara",
			"ohara", "kayak", "puent", "robot", "echue", "cygne", "echut",
			"negro", "ajout", "puera", "trema", "unite", "etait", "boite",
			"lueur", "tueur", "recue", "flute", "hotel", "degre", "verin",
			"perir", "sevre", "maree", "sport", "degat", "style", "phase",
			"tique", "local", "bocal", "focal", "sigle", "benet", "ferue",
			"ledit", "demon", "bemol", "envoi", "envol", "stylo", "actes",
			"gigue", "swing", "nippe", "opere", "lippu", "roche", "aioli",
			"rival", "vivat", "evier", "clair", "raper", "femur", "vivez",
			"river", "rivet", "docte", "leser", "lesez", "entre", "impie",
			"ferie", "pivot", "desir", "slave", "preta", "puine", "beret",
			"vivre", "ample", "prevu", "peril", "ferir", "freta", "prete",
			"heron", "heros", "toast", "seant", "appui", "gigot", "frete",
			"poele", "nique", "aigle", "aigre", "aussi", "style", "divan",
			"metre", "claie", "alain", "aigue", "cigue", "empan", "frene",
			"hiver", "gland", "frele", "paque", "imper", "union", "ocean",
			"divin", "pepin", "repit", "ecole", "treve", "amphi", "oscar",
			"eider", "aider", "vivra", "ampli", "fuira", "nuire", "agile",
			"enter", "luire", "luira", "inter", "ascii", "agira", "esche",
			"impur", "cidre", "ozias", "geant", "ogive", "jesus", "voute",
			"puits", "agita", "agite", "mieux", "april", "vitae", "voute",
			"estce", "agite", "punch", "lunch", "estil", "tuner", "lundi",
			"eclat", "usage", "eclos", "litre", "tuiez", "pitre", "vitre",
			"pepie", "depit", "lofer", "bolee", "usais", "usait", "dogme",
			"antan", "usant", "appel", "huile", "juill", "tract", "aient",
			"tuile", "nuise", "luise", "isard", "puisa", "puise", "intel",
			"nuira", "junte", "patir", "trame", "bogue", "vogua", "rogue",
			"vogue", "vouta", "fuite", "autre", "cieux", "sieur", "pitie",
			"puise", "train", "drain", "traie", "trais", "vogue", "antre",
			"entre", "titan", "trait", "vital", "franc", "liter", "appui",
			"trapu", "piton", "igloo", "siege", "loger", "roger", "algue",
			"punir", "peint", "avais", "tuons", "logis", "aucun", "osait",
			"osais", "appas", "megir", "avant", "megot", "osant", "bater",
			"hater", "tater", "hatez", "usage", "vitre", "dodue", "accru",
			"hatif", "batir", "batit", "apres", "baton", "dogue", "apple",
			"drole", "patre", "ozone", "tenez", "venez", "frank", "theme",
			"brame", "drame", "trama", "tabac", "vendu", "rabat", "beige",
			"ecran", "aller", "these", "venin", "venir", "table", "ecrou",
			"dodge", "veine", "drapa", "tenon", "azote", "renne", "loden",
			"cuber", "roder", "bravo", "tulle", "habit", "devot", "vodka",
			"ecrin", "ecris", "ecrit", "aikin", "ceder", "veine", "feins",
			"feint", "teins", "peins", "drape", "teint", "rabot", "tabou",
			"azote", "subir", "subit", "pizza", "loess", "ecrue", "media",
			"medit", "medis", "table", "vulve", "venue", "tenue", "fente",
			"glebe", "bevue", "aloes", "noeud", "pulse", "avais", "bulbe",
			"teter", "peter", "clerc", "fumer", "fumet", "henne", "fendu",
			"nabab", "rendu", "pendu", "tendu", "acote", "lacet", "denis",
			"tenir", "label", "icone", "benne", "sucer", "lacis", "foehn",
			"bulle", "pacha", "vache", "babil", "dense", "jabot", "nabot",
			"fluet", "pulpe", "scalp", "fable", "myope", "tabla", "nacre",
			"venta", "rente", "pente", "vente", "tente", "bentz", "oubli",
			"boeuf", "avale", "dente", "vente", "nacre", "fixer", "ajonc",
			"rural", "avait", "peler", "durer", "jurer", "avant", "miner",
			"affut", "avala", "ovale", "avale", "acoup", "joker", "humer",
			"ajout", "furie", "purin", "mcgee", "avare", "retif", "juron",
			"beton", "avais", "lacer", "nurse", "avion", "sucez", "retro",
			"usent", "ayons", "opter", "bluff", "optez", "velue", "bacon",
			"usera", "break", "fluer", "blues", "minus", "manes", "pluie",
			"tokyo", "humus", "fluor", "risee", "facto", "pacte", "aucun",
			"mince", "lacte", "belge", "singe", "impot", "furet", "minet",
			"poker", "furia", "mcgee", "burin", "russe", "belon", "luron",
			"sinon", "belle", "telle", "suais", "tempe", "suait", "temps",
			"ainsi", "osent", "quand", "quant", "alias", "suant", "osera",
			"delta", "quasi", "sinus", "engin", "phono", "phone", "frein",
			"verbe", "tolee", "prend", "ouate", "jerez", "verdi", "duper",
			"arene", "arcon", "fuser", "ruser", "doigt", "sceau", "voila",
			"depot", "photo", "silex", "olive", "gilet", "secam", "fusil",
			"poids", "avons", "jupon", "verni", "femme", "suffi", "seide",
			"verso", "joins", "jusqu", "tempo", "point", "siege", "verra",
			"mille", "alibi", "guano", "siera", "juste", "huppe", "buste",
			"foisy", "etale", "quart", "verve", "outil", "perte", "avoir",
			"mufle", "usure", "vertu", "effet", "huppe", "suave", "grege",
			"secte", "ouate", "etang", "etant", "herbe", "derby", "etala",
			"ferai", "xeres", "voici", "berge", "verge", "milan", "perle",
			"ferez", "alize", "etain", "etait", "offre", "perdu", "tonal",
			"exclu", "lupin", "pesez", "peser", "ronge", "mimer", "terne",
			"senat", "rodeo", "bondi", "etape", "derme", "terme", "fondu",
			"perla", "creve", "perle", "rager", "herse", "perse", "poing",
			"joint", "appat", "alite", "verre", "aille", "toile", "boily",
			"poilu", "nonne", "bonde", "fonde", "boira", "boire", "foire",
			"poire", "voire", "vagir", "nervi", "boive", "doive", "boita",
			"boite", "herve", "calin", "roder", "boite", "nonce", "ronce",
			"avenu", "aimer", "poney", "jones", "fonda", "pondu", "tondu",
			"nager", "vagin", "fesse", "genie", "longe", "ronge" };

}
